import Home from './Home';
import BlogDetail from "./BlogDetail";
import Kameraview from './Kameraview';
import Sewaview from './Sewaview';
import Profile from './Profile';
import Search from "./Search";
import AddBlogForm from "./AddBlogForm";
import EditBlogForm from "./EditBlogForm";
import Login from "./Login";
import Register from "./Register";
import SplashScreen from "./SplashScreen";
export {Home, BlogDetail, Kameraview, Sewaview, Profile, Search, AddBlogForm,EditBlogForm, Login,Register,SplashScreen };
